---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


params:
  GOVC_INSECURE:
  GOVC_CA_CERT:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_SSH_KEY:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OPSMAN_DISK_TYPE:
  OM_VM_POWER_STATE:
  OM_VM_FOLDER:


inputs:
  - name: pivnet-opsman-product
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/import-opsman/task.sh